### ISSUE TITLE
1.20.6 is not working

### ISSUE THREAD

**Issue by Zeruu** [Ehhthan/HappyHud-Issues#105]
i have a server running on 1.20.6 and i installed the plugin but it is not working

error message:
[19:20:16 ERROR]: Error occurred while enabling HappyHUD v1.0.13-RELEASE (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at HappyHUD-1.0.13-RELEASE.jar/com.ehhthan.happyhud.api.util.ServerVersion.<init>(ServerVersion.java:10) ~[HappyHUD-1.0.13-RELEASE.jar:?]
        at HappyHUD-1.0.13-RELEASE.jar/com.ehhthan.happyhud.HappyHUD.onEnable(HappyHUD.java:97) ~[HappyHUD-1.0.13-RELEASE.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:357) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1150) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by SanyaCatMeow** [comment]
Have you found a solution?
