### ISSUE TITLE
1.21 Update

### ISSUE THREAD

**Issue by marcocusano** [Ehhthan/HappyHud-Issues#108]
Looking for the 1.21 plugin update:
```SHELL
[12:48:28 ERROR]: Error occurred while enabling HappyHUD v1.0.13-RELEASE (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at HappyHUD-1.0.13-RELEASE.jar/com.ehhthan.happyhud.api.util.ServerVersion.<init>(ServerVersion.java:10) ~[HappyHUD-1.0.13-RELEASE.jar:?]
        at HappyHUD-1.0.13-RELEASE.jar/com.ehhthan.happyhud.HappyHUD.onEnable(HappyHUD.java:97) ~[HappyHUD-1.0.13-RELEASE.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-124-df3b654]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-124-df3b654]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:48:28 INFO]: [HappyHud] Disabling HappyHUD v1.0.13-RELEASE
```

**Comment by marcocusano** [comment]
Solved in [MythicHUD](https://www.spigotmc.org/resources/%E2%AD%90mythichud%E2%AD%90custom-bars-and-number-displays%E2%9C%85replace-vanilla-look%E2%9C%85auto-resource-pack-builder.96299/)
