### ISSUE TITLE
ProtocolLib console spam on 1.19.2

### ISSUE THREAD

**Issue by RoloRotMG** [Ehhthan/HappyHud-Issues#13]
```[14:06:41] [Server thread/ERROR]: [HappyHUD] Unhandled exception occurred in onPacketSending(PacketEvent) for HappyHUD
java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.wrappers.WrappedChatComponent.getJson()" because the return value of "com.comphenix.protocol.reflect.StructureModifier.read(int)" is null
	at com.ehhthan.happyhud.comp.protocollib.ProtocolLibListener$4.onPacketSending(ProtocolLibListener.java:61) ~[HappyHUD-0.1.3-SNAPSHOT.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib(1).jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib(1).jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib(1).jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib(1).jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib(1).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:570) ~[ProtocolLib(1).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:473) ~[ProtocolLib(1).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib(1).jar:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2170) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2156) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.sendActionBar(CraftPlayer.java:2604) ~[pufferfish-1.19.2.jar:git-Pufferfish-33]
	at xyz.rotmc.realm.game.features.player.cooldown.CooldownTask.run(CooldownTask.kt:45) ~[Realm (f181d49).jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.2.jar:git-Pufferfish-33]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[pufferfish-1.19.2.jar:git-Pufferfish-33]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1495) ~[pufferfish-1.19.2.jar:git-Pufferfish-33]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[pufferfish-1.19.2.jar:git-Pufferfish-33]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1419) ~[pufferfish-1.19.2.jar:git-Pufferfish-33]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[pufferfish-1.19.2.jar:git-Pufferfish-33]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-33]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:06:41] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundSetActionBarTextPacket@2d44fc06[
    a=<null>
    components=<null>
  ]
```

Using the latest dev build which is required for 1.19.2 here
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by Ehhthan** [comment]
When I release the newest snapshot this should be fixed.

**Comment by RoloRotMG** [comment]
Ethan I’m gagging for it, any ETA? Wondering if I should release without
happyhud or wait for it to not spew errors at me it’s one of the only
things holding my release back atm :p if you don’t have an eta that’s fine

**Comment by Ehhthan** [comment]
You could also stop whatever could be sending a null action bar for some reason
