### ISSUE TITLE
Cannot use happyhud plugin properly.

### ISSUE THREAD

**Issue by Surtryyds** [Ehhthan/HappyHud-Issues#59]
My server could use the happyhud plugin before, but in the last two days there was a sudden error, probably caused by my updating other plugins, but I don't know exactly what the cause is, and I'm looking for help here, this is the message that reported the error:
<html>
<body>

[10:51:22] [Server thread/WARN]: [HappyHud] Loaded class io.papermc.paper.threadedregions.scheduler.AsyncScheduler from MythicMobs v5.3.3-SNAPSHOT-835ab003 which is not a depend or softdepend of this plugin.
--
561 | [10:51:22] [Server thread/ERROR]: Error occurred while enabling HappyHUD v0.3.5-SNAPSHOT (Is it up to date?)
562 | java.lang.NoSuchMethodError: 'io.papermc.paper.threadedregions.scheduler.AsyncScheduler org.bukkit.Bukkit.getAsyncScheduler()'
563 | at com.ehhthan.libraries.acf.ACFFoliaScheduler.createLocaleTask(ACFFoliaScheduler.java:51) ~[H-HappyHUD-0.3.5-SNAPSHOT.jar:?]
564 | at com.ehhthan.libraries.acf.BukkitCommandManager.<init>(BukkitCommandManager.java:132) ~[H-HappyHUD-0.3.5-SNAPSHOT.jar:?]
565 | at com.ehhthan.libraries.acf.PaperCommandManager.<init>(PaperCommandManager.java:34) ~[H-HappyHUD-0.3.5-SNAPSHOT.jar:?]
566 | at com.ehhthan.happyhud.HappyHUD.registerCommands(HappyHUD.java:167) ~[H-HappyHUD-0.3.5-SNAPSHOT.jar:?]
567 | at com.ehhthan.happyhud.HappyHUD.onEnable(HappyHUD.java:132) ~[H-HappyHUD-0.3.5-SNAPSHOT.jar:?]
568 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
569 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
570 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
571 | at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:611) ~[purpur-1.19.2.jar:git-Purpur-1858]
572 | at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:525) ~[purpur-1.19.2.jar:git-Purpur-1858]
573 | at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1858]
574 | at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1858]
575 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1858]
576 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1858]
577 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
578 | at java.lang.Thread.run(Thread.java:833) ~[?:?]

</body>
</html>

**Comment by Surtryyds** [comment]
Maybe it's not compatible with the mythicmobs plugin?
