### ISSUE TITLE
Plugin didn't work

### ISSUE THREAD

**Issue by DuckLee95** [Ehhthan/HappyHud-Issues#61]
This is the latest plugin

[22:45:48] [Server thread/INFO]: [HappyHud] Enabling HappyHUD v0.3.5-SNAPSHOT
[22:45:49] [Server thread/INFO]: [Plugin] Cracked by Thatundeadperson
[22:45:49] [Server thread/ERROR]: Error occurred while enabling HappyHUD v0.3.5-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.net.URL.toURI()" because the return value of "java.lang.Class.getResource(String)" is null
	at com.ehhthan.happyhud.file.DirectoryCopyFileVisitor.copy(DirectoryCopyFileVisitor.java:21) ~[HappyHUD.jar:?]
	at com.ehhthan.happyhud.HappyHUD.onEnable(HappyHUD.java:76) ~[HappyHUD.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-97]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-97]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.1.jar:git-Paper-97]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.1.jar:git-Paper-97]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-97]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-97]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-97]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-97]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-97]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:45:49] [Server thread/INFO]: [HappyHud] Disabling HappyHUD v0.3.5-SNAPSHOT

**Comment by Ehhthan** [comment]
The problem would appear to be that you are using a cracked version of happy hud. Go fuck yourself :)
