### ISSUE TITLE
[Bug] throws error when using Symlinks for config-folder

### ISSUE THREAD

**Issue by Boy0000** [Ehhthan/HappyHud-Issues#69]
Currently using a symlink between two servers for copying configs over easily
On start-up the following error is then thrown.
This does not happen if i delete the symlink, start, delete the generated folder and add the symlink and reload

```
[19:24:38 INFO]: [HappyHud] Enabling HappyHUD v1.0.4-RELEASE
[19:24:38 ERROR]: [HappyHud] Could not generate default files.
[19:24:38 WARN]: java.nio.file.FileAlreadyExistsException: plugins\HappyHUD
[19:24:38 WARN]:        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:87)
[19:24:38 WARN]:        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[19:24:38 WARN]:        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[19:24:38 WARN]:        at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:521)
[19:24:38 WARN]:        at java.base/java.nio.file.Files.createDirectory(Files.java:700)
[19:24:38 WARN]:        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
[19:24:38 WARN]:        at java.base/java.nio.file.Files.createDirectories(Files.java:753)
[19:24:38 WARN]:        at HappyHUD-1.0.4-RELEASE.jar//com.ehhthan.happyhud.file.DirectoryCopyFileVisitor$1.preVisitDirectory(DirectoryCopyFileVisitor.java:35)
[19:24:38 WARN]:        at HappyHUD-1.0.4-RELEASE.jar//com.ehhthan.happyhud.file.DirectoryCopyFileVisitor$1.preVisitDirectory(DirectoryCopyFileVisitor.java:30)
[19:24:38 WARN]:        at java.base/java.nio.file.Files.walkFileTree(Files.java:2817)
[19:24:38 WARN]:        at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
[19:24:38 WARN]:        at HappyHUD-1.0.4-RELEASE.jar//com.ehhthan.happyhud.file.DirectoryCopyFileVisitor.copy(DirectoryCopyFileVisitor.java:30)
[19:24:38 WARN]:        at HappyHUD-1.0.4-RELEASE.jar//com.ehhthan.happyhud.HappyHUD.onEnable(HappyHUD.java:65)
[19:24:38 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[19:24:38 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[19:24:38 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[19:24:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[19:24:38 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640)
[19:24:38 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551)
[19:24:38 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[19:24:38 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435)
[19:24:38 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[19:24:38 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[19:24:38 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[19:24:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[19:24:38 ERROR]: Error occurred while enabling HappyHUD v1.0.4-RELEASE (Is it up to date?)
java.nio.file.FileSystemAlreadyExistsException: null
        at jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:104) ~[jdk.zipfs:?]
        at java.nio.file.FileSystems.newFileSystem(FileSystems.java:339) ~[?:?]
        at java.nio.file.FileSystems.newFileSystem(FileSystems.java:288) ~[?:?]
        at com.ehhthan.happyhud.file.DirectoryCopyFileVisitor.copy(DirectoryCopyFileVisitor.java:23) ~[HappyHUD-1.0.4-RELEASE.jar:?]
        at com.ehhthan.happyhud.HappyHUD.onEnable(HappyHUD.java:76) ~[HappyHUD-1.0.4-RELEASE.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-131]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-131]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-131]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-131]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-131]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-131]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-131]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-131]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-131]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:24:38 INFO]: [HappyHud] Disabling HappyHUD v1.0.4-RELEASE
```

**Comment by Ehhthan** [comment]
I personally use sym links and don't ever have an issue. I'm not sure if this is a happyhud issue.

**Comment by Boy0000** [comment]
Here I have a server with just HH
1. Generate config like normal
2. Without restarting server, delete generated and create a symlink
3. /hh reload without issues
4. Restart server and get the error

https://streamable.com/ihi3kf
