### ISSUE TITLE
Plugin disable agin. ..

### ISSUE THREAD

**Issue by TheManSoAloNe** [Ehhthan/HappyHud-Issues#90]
```
[20:17:19] [Server thread/INFO]: [HappyHud] Enabling HappyHUD v0.3.5-SNAPSHOT
[20:17:19] [Server thread/INFO]: [HappyHud] Registered translation locale: en_us
[20:17:19] [Server thread/INFO]: [HappyHud] ProtocolLib support detected.
[20:17:19] [Server thread/INFO]: [HappyHud] PlaceholderAPI parser has been registered.
[20:17:19] [Server thread/ERROR]: Error occurred while enabling HappyHUD v0.3.5-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Asset does not exist.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.1-jre.jar:?]
	at com.ehhthan.happyhud.api.element.layout.HudElement.<init>(HudElement.java:24) ~[HappyHUD-0.3.5-SNAPSHOT.jar:?]
	at com.ehhthan.happyhud.api.element.layout.HudLayout.<init>(HudLayout.java:26) ~[HappyHUD-0.3.5-SNAPSHOT.jar:?]
	at com.ehhthan.happyhud.manager.LayoutManager.reload(LayoutManager.java:30) ~[HappyHUD-0.3.5-SNAPSHOT.jar:?]
	at com.ehhthan.happyhud.HappyHUD.reload(HappyHUD.java:153) ~[HappyHUD-0.3.5-SNAPSHOT.jar:?]
	at com.ehhthan.happyhud.HappyHUD.onEnable(HappyHUD.java:126) ~[HappyHUD-0.3.5-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[purpur-1.19.4.jar:git-Purpur-1953]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.4.jar:git-Purpur-1953]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:569) ~[purpur-1.19.4.jar:git-Purpur-1953]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:480) ~[purpur-1.19.4.jar:git-Purpur-1953]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643) ~[purpur-1.19.4.jar:git-Purpur-1953]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442) ~[purpur-1.19.4.jar:git-Purpur-1953]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:344) ~[purpur-1.19.4.jar:git-Purpur-1953]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1953]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1953]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:17:19] [Server thread/INFO]: [HappyHud] Disabling HappyHUD v0.3.5-SNAPSHOT
```

**Comment by Ehhthan** [comment]
Once again you are using old versions.
